# Generated by Django 5.2.4 on 2025-09-02 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentavailability',
            unique_together={('apartment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='apartmentreview',
            unique_together={('apartment', 'user')},
        ),
    ]
