# Generated by Django 5.2.4 on 2025-09-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTourRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('balcony', 'Balcony'), ('terrace', 'Terrace'), ('office', 'Office'), ('hallway', 'Hallway'), ('entrance', 'Entrance'), ('other', 'Other')], max_length=20)),
                ('panoramic_image', models.ImageField(upload_to='virtual_tour/panoramas/')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in virtual tour')),
                ('is_starting_room', models.BooleanField(default=False, help_text='Is this the starting room for the virtual tour?')),
                ('initial_yaw', models.FloatField(default=0.0, help_text='Initial horizontal viewing angle in degrees')),
                ('initial_pitch', models.FloatField(default=0.0, help_text='Initial vertical viewing angle in degrees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tour_rooms', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'Virtual Tour Room',
                'verbose_name_plural': 'Virtual Tour Rooms',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTourHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_type', models.CharField(choices=[('navigation', 'Navigation'), ('info', 'Information'), ('feature', 'Feature Highlight'), ('amenity', 'Amenity')], default='info', max_length=20)),
                ('position_x', models.FloatField(help_text='X position (0.0 to 1.0)')),
                ('position_y', models.FloatField(help_text='Y position (0.0 to 1.0)')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend display', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='apartments.virtualtourroom')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='apartments.virtualtourroom')),
            ],
            options={
                'verbose_name': 'Virtual Tour Hotspot',
                'verbose_name_plural': 'Virtual Tour Hotspots',
            },
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_x', models.FloatField(help_text='X position of hotspot (0.0 to 1.0)')),
                ('hotspot_y', models.FloatField(help_text='Y position of hotspot (0.0 to 1.0)')),
                ('direction_label', models.CharField(blank=True, help_text='Label for the connection (e.g., "To Kitchen", "Exit to Balcony")', max_length=50, null=True)),
                ('transition_yaw', models.FloatField(default=0.0, help_text='Target viewing angle after transition')),
                ('transition_pitch', models.FloatField(default=0.0, help_text='Target pitch angle after transition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='apartments.virtualtourroom')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='apartments.virtualtourroom')),
            ],
            options={
                'verbose_name': 'Room Connection',
                'verbose_name_plural': 'Room Connections',
                'unique_together': {('from_room', 'to_room')},
            },
        ),
    ]
