# Generated by Django 5.2.4 on 2025-09-03 23:10

import apps.apartments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_virtualtourroom_virtualtourhotspot_roomconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtourroom',
            name='panoramic_image',
            field=models.ImageField(help_text='Upload equirectangular panoramic image (2:1 aspect ratio, min 2048x1024, max 10MB)', upload_to='virtual_tour/panoramas/', validators=[apps.apartments.models.validate_panoramic_image]),
        ),
    ]
