# Generated by Django 5.2.4 on 2025-09-05 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_virtualtourroom_panoramic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconnection',
            name='hotspot_color',
            field=models.CharField(default='#D4AF37', help_text='Hotspot color in hex', max_length=7),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='hotspot_size',
            field=models.IntegerField(default=50, help_text='Size of hotspot in pixels'),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='icon',
            field=models.CharField(default='door', help_text='Icon type: door, archway, stairs, elevator, balcony', max_length=50),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this connection is active'),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='pulse_animation',
            field=models.BooleanField(default=True, help_text='Show pulse animation'),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='show_on_hover',
            field=models.BooleanField(default=True, help_text='Show label on hover'),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='transition_animation',
            field=models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='fade', max_length=20),
        ),
        migrations.AddField(
            model_name='roomconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomconnection',
            name='hotspot_x',
            field=models.FloatField(help_text='X position of hotspot (0.0 to 100.0 percent)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='roomconnection',
            name='hotspot_y',
            field=models.FloatField(help_text='Y position of hotspot (0.0 to 100.0 percent)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
